### ISSUE TITLE
concatinating r'' with None

### ISSUE THREAD

**Issue by pvitthal** [Python-scripter/ZCracker#1]
at line 17
self.target_path = r'' + target_path
TypeError: Can't convert 'NoneType' object to str implicitly

we cant concatenate None type with str.

you can replace line 17 with below code
self.target_path = r''+str(target_path)

and there is lot of room to optimize the code

**Comment by MK-Ware** [comment]
Fixed it and added support for rar files. Much thanks for reporting!

**Comment by pvitthal** [comment]
Did couple of changes, check out at https://github.com/2u6z3r0/ZCracker.git, its forked from your repo.
I gave you the git link because I don't know whether the changes will be available to you or not, as this is the first time I forked someones repo.

**Comment by pvitthal** [comment]
got the following error
**from unrar import rarfile as rf
ImportError: No module named 'unrar'**

tried installing unrar via pip3, after installing unrar got below error.
**from unrar import rarfile as rf
  File "/usr/local/lib/python3.5/dist-packages/unrar/rarfile.py", line 26, in <module>
    from unrar import unrarlib
  File "/usr/local/lib/python3.5/dist-packages/unrar/unrarlib.py", line 57, in <module>
    raise LookupError("Couldn't find path to unrar library.")
LookupError: Couldn't find path to unrar library.**

Am I missing anything?

**Comment by MK-Ware** [comment]
I got the same error on windows and I solved it by downloading unrar.dll: http://unrar-dll.soft112.com and placing it in windows\system32.. Might need to do something like that on Linux. Maybe you can find something similar here:

http://www.rarlab.com/rar_add.htm

http://www.linuxfromscratch.org/blfs/view/7.9/general/unrar.html

I'm currently working on a Java version of the same program which should be far more portable, and faster.

I would like to thank you for your interest!
